name: Build

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

env:
  CARGO_TERM_COLOR: always
  OPENSSL_STATIC: "1"
  OPENSSL_NO_VENDOR: "0"

jobs:
  build-linux:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Install musl toolchain
      run: sudo apt-get update && sudo apt-get install -y musl-tools

    - name: Install stable toolchain
      uses: actions-rs/toolchain@v1
      with:
        profile: minimal
        toolchain: stable
        override: true
        target: x86_64-unknown-linux-musl

    - name: Cache
      uses: actions/cache@v4
      with:
        path: |
          ~/.cargo/registry
          ~/.cargo/git
          target
        key: ${{ runner.os }}-cargo-${{ hashFiles('**/Cargo.lock') }}

    - name: Build project
      run: cargo build --release --target=x86_64-unknown-linux-musl

    - name: Run tests
      run: cargo test --release

    - name: Upload Linux Binary
      uses: actions/upload-artifact@v4
      with:
        name: cloudapi-agent
        path: target/x86_64-unknown-linux-musl/release/cloudapi-agent

  # build-windows:
  #   runs-on: windows-latest
  #   steps:
  #   - name: Checkout code
  #     uses: actions/checkout@v3

  #   - name: Cache
  #     uses: actions/cache@v4
  #     with:
  #       path: |
  #         ~/.cargo/registry
  #         ~/.cargo/git
  #         target
  #       key: ${{ runner.os }}-cargo-${{ hashFiles('**/Cargo.lock') }}

  #   - name: Build project (Windows)
  #     run: cargo build --release

  #   - name: Run tests (optional)
  #     run: cargo test --release

  #   - name: Upload Windows Binary
  #     uses: actions/upload-artifact@v4
  #     with:
  #       name: cloudapi-agent.exe
  #       path: target/release/cloudapi-agent.exe